alias vi = nvim
alias chapply = chezmoi apply
alias gst = git status
alias gsw = git switch
alias gck = git checkout
alias grb = git rebase
alias gadd = git add
alias gcm = git commit
alias la = ls -la
alias lg = lazygit
